## Churn Analysis and Customer Intelligence

In [4]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as pyplot
import seaborn as sns
import sqlite3

## 1. Import database / data

In [5]:
# NOTE:
# If you encounter any issues importing the customer_churn.db file,
# run the code below to create the database locally from the provided Excel file OR, can directly import data & start working.

# Otherwise, skip this step and proceed to the next section: Data Import

# Excel file path
# excel_file = 'customer_churn_data_raw.xlsx'

excel_file = 'customer_churn_data_raw.xlsx'

# Create SQLite database connection
# conn = sqlite3.connect('customer_churn.db')

conn  = sqlite3.connect('customer_churn.db')

# Read all sheet names from Excel file
# excel_data = pd.ExcelFile(excel_file)

excel_data = pd.ExcelFile(excel_file)

# Loop through each sheet and store as separate table
# for sheet in excel_data.sheet_names:
#     df = pd.read_excel(excel_file, sheet_name=sheet) # Read sheet into dataframe
#     # Write dataframe to SQLite table
#     df.to_sql(
#         name=sheet,          # Table name = Sheet name
#         con=conn,
#         if_exists='replace', # Replace table if already exists
#         index=False
#     )


for sheet in excel_data.sheet_names:
    df = pd.read_excel(excel_file , sheet_name = sheet)  # read sheet into dataframe
     # Write dataframe to SQLite table
    df.to_sql(
        name=sheet,
        con=conn,
        if_exists = 'replace',  # Replace table if already exists
        index=False
    )
    


# Close connection
# conn.close()

conn.close()

print("All sheets successfully converted into SQLite tables.")

All sheets successfully converted into SQLite tables.

In [6]:
# Data Import: db file to pandas, storing each table to a separate df

# Connect to SQLite database

conn = sqlite3.connect('customer_churn.db')

# sql query to Get all table names

sql_query = """SELECT name 
            FROM sqlite_master
            WHERE type='table';
            """

# read sql query in pandas

tables = pd.read_sql_query(sql_query, conn)


# create dataframe for each table

for table_name in tables['name']:
    df = pd.read_sql(f"SELECT * FROM {table_name}", conn)  # Read table into dataframe
    globals()[f"df_{table_name}"] = df   # Create dynamic dataframe name
    print(f"Created dataframe: df_{table_name}")
    



# Close connection

conn.close()

Created dataframe: df_db_customer
Created dataframe: df_db_subscription
Created dataframe: df_db_support

In [7]:
# Print table names and column names

conn = sqlite3.connect('customer_churn.db')

In [8]:
for table_name in tables['name']:
    print(f"\n Table Name : {table_name}")
    # Get column information
    columns_query = f"PRAGMA table_info({table_name});"
    columns = pd.read_sql_query(columns_query, conn)
    print("Columns:")

    print(columns['name'].tolist())


# Close connection
conn.close()

 Table Name : db_customer
Columns:
['customerid', 'name', 'country', 'state', 'gender', 'dob', 'interests', 'pincode']

 Table Name : db_subscription
Columns:
['customerid', 'subscription_start_date', 'subscription_type', 'renewal_date', 'plan_type', 'contract_type', 'cancellation_date', 'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score']

 Table Name : db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

In [9]:
# PRAGMA is a special command in SQLite used to:
# inspect db information, control db settings, retrieve metadata about tables

## 2. Data cleaning

In [10]:
df_db_customer.head() # customer table 
df_db_customer.tail() # customer table

,customerid,name,country,state,gender,dob,interests,pincode
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,None,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,None,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,None,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,None,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,None,None

In [11]:
df_db_customer.info() # customer table

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     object
 1   name        21 non-null     object
 2   country     18 non-null     object
 3   state       21 non-null     object
 4   gender      21 non-null     object
 5   dob         21 non-null     object
 6   interests   4 non-null      object
 7   pincode     0 non-null      object
dtypes: object(8)
memory usage: 1.4+ KB

In [12]:
# a. rename col - name to customer_name
# b. drop columns - interest and pincode
# c. change data type - dob
# d. data standardization - gender
# e. fix missing values (using existing data) - country

#### a. Rename Col

In [13]:
# a. rename col - name to customer_name

df_db_customer.rename(columns = {'name' : 'customer_name'}, inplace= True)

#### b. Drop columns

In [ ]:
# df_db_customer.columns[-2:]

# df_db_customer.columns[6:] target columns in positive index 

# different methods to drop columns in pandas dataframe

# df_db_customer.drop(df_db_customer.columns[-2:] , axis=1 , inplace = True)


# df_db_customer.drop(columns = ['interest', 'pincode' , axis=1 ])

#### c. Change data type

In [20]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     object
 1   customer_name  21 non-null     object
 2   country        18 non-null     object
 3   state          21 non-null     object
 4   gender         21 non-null     object
 5   dob            21 non-null     object
dtypes: object(6)
memory usage: 1.1+ KB

In [25]:
# DOB 

df_db_customer['dob']  =  pd.to_datetime(df_db_customer['dob'])

#### d. Data standardization

In [31]:
# gender 

# df_db_customer['gender'].unique()

df_db_customer['gender'] = df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

In [32]:
df_db_customer['gender'].unique()

array(['Male', 'Female'], dtype=object)

#### e. Fix missing values

In [ ]:
# country 

# df_db_customer['country'].isnull().sum()
df_db_customer['country'].isna().sum()

np.int64(3)

In [36]:
df_db_customer[df_db_customer['country'].isna()]

    customerid customer_name country      state  gender        dob
5   0013-MHZWF         durga    None      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya    None  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra    None  Telangana  Female 2004-12-01

In [38]:
# normal way 

# df_db_customer['country'].fillna('Nahi pata ')

df_db_customer[['country', 'state']]

   country          state
0    India    Maharashtra
1    India      Karnataka
2    India          Delhi
3    India       Nagaland
4    India          Delhi
5     None          Delhi
6    India      Meghalaya
7    India      Rajasthan
8     None      Kathmandu
9    Nepal      Kathmandu
10   India    Maharashtra
11   India      Karnataka
12    None      Telangana
13   India      Meghalaya
14   India  Uttar Pradesh
15   India          Delhi
16   India      Meghalaya
17   India      Rajasthan
18   India      Telangana
19   India  Uttar Pradesh
20   India    Maharashtra

In [44]:
# country and state - unique value pair

# Creating state → country map from non-null rows

state_country_mapping = df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()

# Fill the missing country using State

df_db_customer['country'] =   df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))

In [45]:
df_db_customer[df_db_customer['country'].isna()]

Empty DataFrame
Columns: [customerid, customer_name, country, state, gender, dob]
Index: []

## 2. for subscription head table

In [48]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,None,None,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,None,None,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,None,None,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

In [50]:
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     object
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     object
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      object
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), object(8)
memory usage: 1.9+ KB

In [51]:
# change data type to date - subscription_start_date , renewal_date, cancellation_date

date_col = ['subscription_start_date' , 'renewal_date' , 'cancellation_date']

df_db_subscription[date_col] = df_db_subscription[date_col].apply(pd.to_datetime)

In [52]:
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     datetime64[ns]
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     datetime64[ns]
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      datetime64[ns]
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(5)
memory usage: 1.9+ KB

## 3. for support  head table

In [61]:
df_db_support

   customerid       complaint_date escalations  csat_score
0  0003-MKNFE  2024-08-28 00:00:00           N          60
1  0003-MKNFE  2024-08-28 00:00:00           Y          10
2  0013-EXCHZ  2024-01-20 00:00:00           Y          20
3  0013-MHZWF  2025-03-18 00:00:00           N          90
4  0013-SMEOE  2024-11-01 00:00:00           N          30
5  0017-IUDMW  2024-04-10 00:00:00           Y          25
6  0019-EFAEP  2024-09-27 00:00:00           Y          30
7  0022-TCJCI  2024-09-13 00:00:00           Y          10
8  0022-TCJCI  2024-09-14 00:00:00           N          90

In [57]:
df_db_support.head()

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,None
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,None

In [55]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      object
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [59]:
#  drop column 

df_db_support.drop(columns=['col_1' , 'comment'] , axis=1 , inplace=True)

In [62]:
# change data type to date - complaint_date

df_db_support['complaint_date'] = pd.to_datetime(df_db_support['complaint_date'])

In [63]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      datetime64[ns]
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 420.0+ bytes

## 3. Feature Engineering & Data Analysis